# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87f7eab1e4fb3fb7e5a7941ec98742095109a8126d2d6267f25cad165178606cc0840d79c57e4a66d8c47d95348a7a52d0ad752c1a5293aa14640fe2169223e2

test:
  secret_key_base: 5a2bc7bc45efaf923180af8ba2b8e203b521e0df12848ae7d78e53bca4e5c44e8720aa2ca2284df5179af8c5c9fbc47403ddb9392a189664d9c4d0f0ff37a665

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
